services:
  zonos:
    container_name: "zonos"
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    network_mode: "host"
    stdin_open: true
    tty: true
    command: ["python3", "gradio_interface.py"]
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - GRADIO_SHARE=False
    user: 0:0
    ports:
        - 7860:7860 # web ui
        - 7861:7861 # api
    volumes:
      - ./zonos:/root/.cache